services:
  postgres:
    image: postgres:16-alpine
    container_name: pack-assistant-db
    environment:
      POSTGRES_DB: pack_assistant
      POSTGRES_USER: pack_assistant
      POSTGRES_PASSWORD: pack_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pack_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  